import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col justify-between">
        <Header /> 
        <main id="main-content" role="main" aria-label="Main content">
          {children}
        </main>
        <footer className="bg-white border-t border-slate-200 mt-16" role="contentinfo">
          <div className="container py-6">
            <p className="text-sm text-slate-400 text-center">
              © {new Date().getFullYear()} HousePredictor. All rights reserved.
            </p>
          </div>
        </footer> 
      </body> 
    </html>
  );
}
